#!/bin/bash

if [ -z "$PYFILE" ]; then
  echo "Error: Environment variable PYFILE is not set."
  exit 1

fi 

output_filename="${PYFILE}c"
echo "Compiling $PYFILE ..."

python3 -m py_compile "$PYFILE"

if [ -f "$output_filename" ]; then
  echo "Compilation successful. Output filename: $output_filename"
else
  echo "Compilation failed."
fi 
